services:
  mongodb:
    image: contact-log-db-image
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
